# Configuration for Javier Campos's Personal Site

# --- Required options ---
title: "Javier Campos | AI & Business Growth Expert"
author: Francisco Javier Campos Zabala

# --- Navigation ---
navbar-links:
  About Me/Contact: "author/"
  Book:
    - Buy the Book: "https://www.dpbolvw.net/click-101158208-12898971?url=https%3A%2F%2Flink.springer.com%2Fbook%2F10.1007%2F978-1-4842-9669-1"
    - Summary Book: "summary-book/"
    - Code & Resources: "references/"
  Podcasts:
    - Business Growth with AI: "How to grow your business with AI.wav"
    - AI MythBusters: "https://shows.acast.com/mythbusters-ai-edition-for-adtech-pioneers"
  Newsletter: "Firstnewsletter/"
  Articles: "Javier Campos Article.pdf"

# --- Logo ---
title-img: "/assets/img/book-cover.jpg"

# --- Footer social media links ---
social-network-links:
  email: "javcamposz@hotmail.com"
  linkedin: camposjavier
  facebook: javcamposz
  github: javcamposz
  twitter: javcamposz
  youtube: "www.youtube.com/@JavierCamposMythBusterAI"
  rss: true

# --- General options ---
url-pretty: "javiercampos.ai"

# --- Colour / background options ---
navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# --- Thumbnail size options ---
thumbnail-size: 250

# --- Analytics ---
gtag: "G-H83V6SRTMF"

# Don't include a page date
page-date: false

# Don't show the "Next post" and "Previous post" links
post-navigation: false

# Enable pagination
paginate: 5

# Enable comments (via Disqus)
# disqus: "your-disqus-shortname"

# Output options (more information on Jekyll's site)
timezone: "London"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/

kramdown:
  input: GFM

# Default YAML values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189