# Improved configuration for Javier Campos's Personal Site

# --- Required options ---
title: "Javier Campos | AI & Business Growth Expert"
author: "Francisco Javier Campos Zabala"

# --- Navigation ---
navbar-links:
  About: "about/"
  Book:
    - Buy the Book: "https://www.dpbolvw.net/click-101158208-12898971?url=https%3A%2F%2Flink.springer.com%2Fbook%2F10.1007%2F978-1-4842-9669-1"
    - Summary: "summary-book/"
    - Code & Resources: "resources/"
  Podcast:
    - Business Growth with AI: "podcast/business-growth-ai/"
    - AI MythBusters: "https://shows.acast.com/mythbusters-ai-edition-for-adtech-pioneers"
  Articles:
    - Implementing LLMs: "articles/implementing-llms/"
    - All Articles: "articles/"
  Newsletter: "newsletter/"
  Contact: "contact/"

# --- Logo & Branding ---
title-img: "/assets/img/javier-campos-logo.png"
favicon: "/assets/img/favicon.ico"

# --- Footer social media links ---
social-network-links:
  email: "javcamposz@hotmail.com"
  linkedin: camposjavier
  twitter: javcamposz
  github: javcamposz
  youtube: "@JavierCamposMythBusterAI"
  facebook: javcamposz

# --- Sharing options ---
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# --- Website Settings ---
url-pretty: "javiercampos.ai"
google_analytics: "G-H83V6SRTMF"

# --- Theme Colors ---
navbar-col: "#FFFFFF"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# --- Fonts ---
# Add Google Fonts
google_fonts:
  - "Roboto:300,400,700"
  - "Open Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"

# Use Google Fonts
font-family: "Roboto, 'Open Sans', sans-serif"

# --- Additional Customization ---
# Add custom CSS
extra_css:
  - "/assets/css/custom-styles.css"

# Enable dark mode toggle
dark_mode: true

# Add a cookie consent banner
cookie_consent:
  enabled: true
  message: "This website uses cookies to ensure you get the best experience."
  dismiss: "Got it!"
  link: "Learn more"

# Enable a back-to-top button
back_to_top: true

# Add reading time estimate to posts
reading_time: true

# Enable table of contents for posts
toc:
  enabled: true
  h_min: 2
  h_max: 3

# --- SEO Optimization ---
description: "Javier Campos - Expert in AI and business growth strategies. Author, speaker, and consultant helping businesses leverage AI for success."
keywords: "AI, artificial intelligence, business growth, digital transformation, machine learning, consulting"

# --- Performance Optimization ---
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []

# Exclude unnecessary files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - vendor/

# --- Plugin Settings ---
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Pagination settings
paginate: 6
paginate_path: "/page:num/"

# RSS Feed
feed:
  path: feed.xml

# Sitemap settings
sitemap:
  filename: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"