# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Francisco Javier Campos - AI & Business Growth Expert"
title_separator          : "-"
subtitle                 : "AI Innovation, Ethical AI Deployment & AI Safety Frameworks"
name                     : "Francisco Javier Campos Zabala"
description              : "Technology leader specializing in AI innovation, ethical AI deployment, and AI safety frameworks. Expert in scaling AI solutions across industries with extensive experience in marketing, telco, and financial services."
url                      : "https://javcamposz.github.io"
baseurl                  : ""
repository               : "javcamposz/javcamposz.github.io"
teaser                   : "/assets/img/JavierCampos.jpg"
logo                     : "/assets/img/JavierCampos.jpg"
masthead_title           : "AI Horizons"
breadcrumbs              : false
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  hide                   : false
search                   : true
search_full_content      : true
search_provider          : lunr

# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               : javcamposz
facebook:
  username               : javcamposz
og_image                 : "/assets/img/JavierCampos.jpg"

# For specifying social profiles
social:
  type                   : Person
  name                   : Francisco Javier Campos Zabala
  links:
    - "https://www.linkedin.com/in/camposjavier/"
    - "https://github.com/javcamposz"
    - "https://twitter.com/javcamposz"

# Analytics
analytics:
  provider               : google
  google:
    tracking_id          : "G-H83V6SRTMF"
    anonymize_ip         : true

# Site Author
author:
  name             : "Francisco Javier Campos Zabala"
  avatar           : "/assets/img/JavierCampos.jpg"
  bio              : "Technology leader specializing in AI innovation, ethical AI deployment, and AI safety frameworks. Expert in scaling AI solutions across industries."
  location         : "London, UK"
  email            : "javcamposz@hotmail.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/camposjavier/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/javcamposz"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/javcamposz"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@JavierCamposMythBusterAI"

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/camposjavier/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/javcamposz"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/javcamposz"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@JavierCamposMythBusterAI"
  since: "2020"

# Reading Files
include:
  - .htaccess
  - _pages

# Outputting
permalink: /:categories/:title/
timezone: Europe/London
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
